### ISSUE TITLE
Polybar problem[its actually wibox]

### ISSUE THREAD

**Issue by alessandroDeIturbe** [hans3I/dots#1]
![2022-10-08_15-40](https://user-images.githubusercontent.com/63016931/194710595-48d7359a-9c54-485c-93f2-9b2d0b7ec4eb.png)
I've tried to install it, but polybar have some problems (this is the screenshot of my two screens togheter)

**Comment by hans3I** [comment]
@alessandroDeIturbe I'm using polybar when I'm using bspwm, when I'm using awesomewm I use the builtin bar(wibox). Actually the only config you need to use is awesomewm alacritty and neovim(if you want)

**Comment by hans3I** [comment]
@alessandroDeIturbe You have to edit the posisition of the bar yourself, its in the rc.lua file row 267. Just change the value of **x** and the **width**, plus it's actually wibox not polybar. Hope this helps ^-^

**Comment by alessandroDeIturbe** [comment]
thx
